# Generated by Django 5.2.6 on 2025-11-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_remove_itemventa_subtotal_itemventa_sub_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemventa',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Subtotal'),
        ),
    ]
