# Generated by Django 5.2.6 on 2025-11-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='codigo',
            field=models.BigIntegerField(verbose_name='Codigo de venta'),
        ),
    ]
