# Generated by Django 5.2.6 on 2025-10-31 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_producto_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientostock',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Movimientos de Stocks'},
        ),
    ]
