# Generated by Django 5.2.6 on 2025-11-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_movimientostock_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_unitario',
        ),
    ]
